### ISSUE TITLE
Support "sparserevlog" feature

### ISSUE THREAD

**Issue by dblsaiko** [kilork/hg-git-fast-import#19]
Currently this doesn't seem to support the "sparserevlog" feature, so when trying to import a repository that uses it you get

```
thread 'main' panicked at 'could not parse requirement: UnknownRequirement("sparserevlog")', /home/saiko/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.5.0/src/lib.rs:381:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: hg_parser::MercurialRepository::load_requires
   4: hg_git_fast_import::single::hg2git
   5: hg_git_fast_import::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kilork** [comment]
@2xsaiko Hi, I do not think it would support this feature, I almost stopped activity on this project, but my observation  was, that probably you can just ignore this. Please, read more here: https://github.com/kilork/hg-git-fast-import/issues/11

I had feeling, I added this option for cli, but seems like not.

**Comment by dblsaiko** [comment]
Oh oops, I thought I looked at existing issues (I guess I just didn't look at closed ones). Thanks!

**Comment by kilork** [comment]
I think probably closing previous bug was a mistake, so let's try to keep this one and really fix it.
