### ISSUE TITLE
range end index ... out of range for slice of length ...

### ISSUE THREAD

**Issue by Scraft** [kilork/hg-git-fast-import#20]
I have a large repository (90 odd GB) used for a game, so a lot of textures/audio alongside code, I am in the process of converting it from Mercurial to Git. It has failed a couple of times at the same place, I have had results like:

```
/mnt/d/Repo2/hg-git-fast-import$ hg-git-fast-import single --config ../hg/repo/config.toml --fix-wrong-branch-names ../hg/repo/ ../git/repo
⠁[02:18:37] [███████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]  12393/16913 (3h)
thread '<unnamed>' panicked at 'range end index 18446744071782745169 out of range for slice of length 2368160849', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.5.0/src/revisionlog.rs:534:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

or, attempting to get more backtrace:

```
/mnt/d/Repo2/hg-git-fast-import$ RUST_BACKTRACE=1 hg-git-fast-import single --config ../hg/repo/config.toml --fix-wrong-branch-names ../hg/repo/ ../git/repo
⠁[01:56:55] [███████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]  12393/16913 (2h)
thread '<unnamed>' panicked at 'range end index 18446744071782745169 out of range for slice of length 2368160849', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.5.0/src/revisionlog.rs:534:26
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
   2: core::slice::slice_end_index_len_fail
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/slice/mod.rs:3149
   3: hg_parser::revisionlog::FragmentWrapperIterator::delta
   4: hg_parser::revisionlog::RevisionLog::construct_simple
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   6: rayon::iter::plumbing::bridge_producer_consumer::helper
   7: rayon_core::job::StackJob<L,F,R>::run_inline
   8: rayon::iter::plumbing::bridge_producer_consumer::helper
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  14: rayon_core::registry::WorkerThread::wait_until_cold
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  17: rayon_core::registry::WorkerThread::wait_until_cold
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: rayon_core::job::StackJob<L,F,R>::run_inline
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  23: rayon_core::registry::WorkerThread::wait_until_cold
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  26: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'range end index 18446744071782745169 out of range for slice of length 2368160849', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.5.0/src/revisionlog.rs:534:26
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
   2: core::slice::slice_end_index_len_fail
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/slice/mod.rs:3149
   3: hg_parser::revisionlog::FragmentWrapperIterator::delta
   4: hg_parser::revisionlog::RevisionLog::construct_simple
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   6: rayon::iter::plumbing::bridge_producer_consumer::helper
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon::iter::plumbing::bridge_producer_consumer::helper
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  13: rayon_core::registry::WorkerThread::wait_until_cold
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  16: rayon_core::registry::WorkerThread::wait_until_cold
  17: rayon::iter::plumbing::bridge_producer_consumer::helper
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  20: rayon_core::registry::WorkerThread::wait_until_cold
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
  23: rayon::iter::plumbing::bridge_producer_consumer::helper
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  26: rayon_core::registry::WorkerThread::wait_until_cold
⠄[01:58:01] [███████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]  12399/16913 (2h)
thread 'main' panicked at 'Cannot get data from thread: Any', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/ordered-parallel-iterator-0.1.1/src/lib.rs:112:42
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
   2: core::result::unwrap_failed
             at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
   3: <ordered_parallel_iterator::OrderedParallelIterator<T> as core::iter::traits::iterator::Iterator>::next
   4: hg_git_fast_import::single::hg2git
   5: hg_git_fast_import::main
```

I appreciate that without having access to the repository it is possibly hard for you, but I wondered if you had any thoughts?

**Comment by Scraft** [comment]
I found I could go to revision 12401 (--limit-hight 12401) without a problem:

```
/mnt/d/Repo2/hg-git-fast-import$ RUST_BACKTRACE=full hg-git-fast-import single --config ../hg/repo/config.toml --fix-wrong-branch-names --limit-high 12401 ../hg/repo/ ../git/repo
 [00:00:00] [█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] Repository ../hg/repo/ [12401;12401). Elapsed: 0 seconds (0s)
HEAD is now at 678c4cd17 Merge
Finished. Time elapsed: 32 seconds
```

And from there, increasing it to 12402 (--limit-high 12402), causes it to go wrong. I changed the RUST_BACKTRACE to full too:

```
/mnt/d/Repo2/hg-git-fast-import$ RUST_BACKTRACE=full hg-git-fast-import single --config ../hg/repo/config.toml --fix-wrong-branch-names --limit-high 12402 ../hg/repo/ ../git/repo
thread '<unnamed>' panicked at 'range end index 18446744071782745169 out of range for slice of length 2368160849', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.5.0/src/revisionlog.rs:534:26
stack backtrace:
   0:     0x7f1b0941dc80 - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7f1b0941dc80 - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7f1b0941dc80 - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x7f1b0941dc80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x7f1b092eecdf - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x7f1b09415744 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x7f1b094329d0 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x7f1b094329d0 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x7f1b094329d0 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x7f1b094331d0 - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x7f1b094331d0 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x7f1b0941e038 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x7f1b0941e004 - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x7f1b0943192d - rust_begin_unwind
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x7f1b092ed390 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x7f1b092ec961 - core::slice::slice_end_index_len_fail::h9914c0a7dd0ab297
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/slice/mod.rs:3149
  16:     0x7f1b09357e19 - hg_parser::revisionlog::FragmentWrapperIterator::delta::hb7fb457102eebdc4
  17:     0x7f1b093536f6 - hg_parser::revisionlog::RevisionLog::construct_simple::h748fb3252a56f174
  18:     0x7f1b0934df8d - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::he83965c1bc04e8c0
  19:     0x7f1b09331f8e - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  20:     0x7f1b09332553 - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  21:     0x7f1b09332553 - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  22:     0x7f1b09332553 - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  23:     0x7f1b09332553 - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  24:     0x7f1b09332553 - rayon::iter::plumbing::bridge_producer_consumer::helper::h17a818edcd40d5ba
  25:     0x7f1b0934998f - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h91352652d706a570
  26:     0x7f1b0938d9f2 - rayon_core::registry::WorkerThread::wait_until_cold::h63d11b623e9a640f
  27:     0x7f1b09391415 - std::sys_common::backtrace::__rust_begin_short_backtrace::h02791cafe4479e39
  28:     0x7f1b09391856 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h27d380f22419126d
  29:     0x7f1b094338ca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h82ab465ddb64eba2
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/alloc/src/boxed.rs:1042
  30:     0x7f1b094338ca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5aa0c3a5cb1c92ed
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/alloc/src/boxed.rs:1042
  31:     0x7f1b094338ca - std::sys::unix::thread::Thread::new::thread_start::ha82b07ed1fc4982c
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys/unix/thread.rs:87
  32:     0x7f1b085d76db - start_thread
  33:     0x7f1b08b2171f - __clone
  34:                0x0 - <unknown>
thread 'main' panicked at 'Cannot get data from thread: Any', /home/scraft/.cargo/registry/src/github.com-1ecc6299db9ec823/ordered-parallel-iterator-0.1.1/src/lib.rs:112:42
stack backtrace:
   0:     0x7f1b0941dc80 - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7f1b0941dc80 - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7f1b0941dc80 - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x7f1b0941dc80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x7f1b092eecdf - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x7f1b09415744 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x7f1b094329d0 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x7f1b094329d0 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x7f1b094329d0 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x7f1b094331d0 - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x7f1b094331d0 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x7f1b0941e038 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x7f1b0941e004 - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x7f1b0943192d - rust_begin_unwind
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x7f1b092ed390 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x7f1b092ee7e2 - core::result::unwrap_failed::h24cfbc9782f4fe17
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
  16:     0x7f1b09388204 - <ordered_parallel_iterator::OrderedParallelIterator<T> as core::iter::traits::iterator::Iterator>::next::h36f61db6c3dd6b96
  17:     0x7f1b0925c83a - hg_git_fast_import::single::hg2git::hd86360abe4142cbd
  18:     0x7f1b0923d947 - hg_git_fast_import::main::hc4984c68c07ff378
  19:     0x7f1b0943d553 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3cde3c071bc0b5b5
  20:     0x7f1b09239751 - main
  21:     0x7f1b08a21bf7 - __libc_start_main
  22:     0x7f1b09237c9a - _start
  23:                0x0 - <unknown>
```

**Comment by Scraft** [comment]
This seems to fix it: https://github.com/kilork/hg-parser/pull/3

**Comment by kilork** [comment]
@Scraft hi, thank you for analysis and fix. I had not been working on this for a while, I would take a look this weekend, it seems to be completely fine to merge 👍

**Comment by kilork** [comment]
Closing this now, seems like I just forgot to do so last time.
